name: 'Check Terraform Configuration'

on:
  push:
    branches:
      - nope
  pull_request_target:
    branches:
      - nope

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
